"""
isolane/provisioner/steps/prometheus_scrape.py

Write a per-namespace Prometheus scrape config.
"""

import os
import textwrap
from typing import Any
from pathlib import Path


def run(ns: str, cfg: dict[str, Any]) -> None:
    scrape_dir   = Path(os.environ.get(
        "PROMETHEUS_SCRAPE_DIR",
        "./monitoring/prometheus/scrape_configs",
    ))
    scrape_dir.mkdir(parents=True, exist_ok=True)

    worker_host  = os.environ.get("WORKER_HOST", "engine-worker")
    metrics_port = os.environ.get("WORKER_METRICS_PORT", "9090")

    config = textwrap.dedent(f"""\
        # Auto-generated by isolane provisioner for namespace: {ns}
        # DO NOT EDIT — regenerate with: make tenant ns={ns}
        # Regenerated on: {{timestamp}}
        - job_name: 'engine-{ns}'
          honor_labels: false
          metrics_path: '/metrics/{ns}'
          scrape_interval: 30s
          static_configs:
            - targets: ['{worker_host}:{metrics_port}']
              labels:
                tenant: '{ns}'
    """)

    from datetime import datetime, timezone
    config = config.replace(
        "{timestamp}",
        datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )

    config_file = scrape_dir / f"{ns}.yml"
    config_file.write_text(config)

    print(f"  [prometheus_scrape] Scrape config written to {config_file}")
    print(f"  [prometheus_scrape] Endpoint: {worker_host}:{metrics_port}/metrics/{ns}")
    print(f"  [prometheus_scrape] Label injected: tenant={ns}")