scrape_configs:
  - job_name: 'engine-brand_a'
    honor_labels: false
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['engine-worker:9090']
        labels:
          tenant: 'brand_a'

  - job_name: 'go-worker-brand_a'
    honor_labels: false
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['go-worker:9090']
        labels:
          tenant: 'brand_a'
